/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.SchoolAdmin;

import Business.Enterprize.Enterprize;
import Business.Enterprize.School;
import Business.Funds.Funds;
import Business.Funds.HealthFunds;
import Business.Funds.InfraFunds;
import Business.Funds.StationaryFunds;
import Business.Role.SchoolAdminRole;
import Business.Users.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Dell
 */
public class ManageFinances extends javax.swing.JPanel {

    /**
     * Creates new form LoginPage
     */
    JPanel container;
    private School enterprise;
    private UserAccount account;
    private double infrafunds, stationaryfunds, healthfunds;

    public ManageFinances(JPanel container, UserAccount account, Enterprize enterprise) {
        initComponents();
        this.container = container;
        this.enterprise = (School) enterprise;
        this.account = account;
        this.infrafunds = this.enterprise.getInfraFunds();
        this.stationaryfunds = this.enterprise.getStationaryFunds();
        this.healthfunds = this.enterprise.getHealthFunds();
        populatecombobox();
    }

    public void load() {
        final Timer t = new Timer(200, (ActionEvent e) -> {
            simulate();
            if (jProgressBar2.getValue() == 30) {
                ((Timer) e.getSource()).stop();
            }
        });
        t.start();
    }

    public void simulate() {
        double infra = enterprise.getInfraScore() * 100;
        double util = enterprise.getStationaryScore() * 100;
        double health = enterprise.getHealthScore() * 100;
        if (fundsCombo.getSelectedIndex() == 0) {
            txtFunds.setText("");
        }
        if (fundsCombo.getSelectedIndex() == 1) {
            txtFunds.setText(String.valueOf(enterprise.getInfraFunds()));
            jProgressBar2.setValue((int) infra);
        }
        if (fundsCombo.getSelectedIndex() == 2) {
            txtFunds.setText(String.valueOf(enterprise.getStationaryFunds()));
            jProgressBar2.setValue((int) util);
        }
        if (fundsCombo.getSelectedIndex() == 3) {
            txtFunds.setText(String.valueOf(enterprise.getHealthFunds()));
            jProgressBar2.setValue((int) health);
        }
    }

    public void populatecombobox() {
        fundsCombo.removeAllItems();
        fundsCombo.addItem(null);
        fundsCombo.addItem(Funds.fundsType.InfraFunds);
        fundsCombo.addItem(Funds.fundsType.StationaryFunds);
        fundsCombo.addItem(Funds.fundsType.HealthCareFunds);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userProcessContainer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fundsCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtFunds = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Select Funds Type:");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Manage Finances");

        fundsCombo.setBackground(new java.awt.Color(255, 0, 51));
        fundsCombo.setEditable(true);
        fundsCombo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        fundsCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fundsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundsComboActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Total Funds Available:");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Score:");

        jProgressBar2.setBackground(new java.awt.Color(51, 51, 255));
        jProgressBar2.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar2.setStringPainted(true);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Enter Amount required:");

        BackButton.setBackground(new java.awt.Color(255, 0, 51));
        BackButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 102));
        BackButton.setText("<<Back");
        BackButton.setBorder(null);
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userProcessContainerLayout = new javax.swing.GroupLayout(userProcessContainer);
        userProcessContainer.setLayout(userProcessContainerLayout);
        userProcessContainerLayout.setHorizontalGroup(
            userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProcessContainerLayout.createSequentialGroup()
                .addGroup(userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userProcessContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userProcessContainerLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(94, 94, 94)
                        .addGroup(userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFunds, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(fundsCombo, 0, 309, Short.MAX_VALUE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userProcessContainerLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                    .addContainerGap(446, Short.MAX_VALUE)))
        );
        userProcessContainerLayout.setVerticalGroup(
            userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProcessContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BackButton))
                .addGap(50, 50, 50)
                .addGroup(userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fundsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(txtFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
            .addGroup(userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userProcessContainerLayout.createSequentialGroup()
                    .addGap(236, 236, 236)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(45, 45, 45)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(237, Short.MAX_VALUE)))
        );

        loginButton.setBackground(new java.awt.Color(255, 0, 51));
        loginButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 102));
        loginButton.setText("Request Amount");
        loginButton.setBorder(null);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(userProcessContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(userProcessContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fundsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundsComboActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_fundsComboActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        double diff = 0;
        if (fundsCombo.getSelectedIndex() == 1) {
            diff = InfraFunds.getMaxLimit() - enterprise.getInfraFunds();
            if (Double.parseDouble(txtAmount.getText()) > diff) {
                JOptionPane.showMessageDialog(null, "Amount exceeded max limit!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            WorkRequest request = new WorkRequest();
            request.setFundType(Funds.fundsType.InfraFunds.getValue());
            request.setSender(account);
            enterprise.getUserAccountDirectory().getUserAccount().stream()
                    .filter(x -> x.getRole() instanceof SchoolAdminRole)
                    .forEach(x -> {
                        request.setReceiver(x);
                        request.setFundRequested(Double.parseDouble(txtAmount.getText()));
                        request.setGrantStatus("In Transit");
                        x.getWorkQueue().getWorkRequestList().add(request);
                    });
            JOptionPane.showMessageDialog(null, "Sent request to school admin!", "Sent", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if (fundsCombo.getSelectedIndex() == 2) {
            diff = StationaryFunds.getMaxLimit() - enterprise.getStationaryFunds();
            if (Double.parseDouble(txtAmount.getText()) > diff) {
                JOptionPane.showMessageDialog(null, "Amount exceeded max limit!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            WorkRequest request = new WorkRequest();
            request.setFundType(Funds.fundsType.StationaryFunds.getValue());
            request.setSender(account);
            enterprise.getUserAccountDirectory().getUserAccount().stream()
                    .filter(x -> x.getRole() instanceof SchoolAdminRole)
                    .forEach(x -> {
                        request.setReceiver(x);
                        request.setFundRequested(Double.parseDouble(txtAmount.getText()));
                        request.setGrantStatus("In Transit");
                        x.getWorkQueue().getWorkRequestList().add(request);
                    });
            JOptionPane.showMessageDialog(null, "Sent request to school admin!", "Sent", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if (fundsCombo.getSelectedIndex() == 3) {
            diff = HealthFunds.getMaxLimit() - enterprise.getHealthFunds();
            if (Double.parseDouble(txtAmount.getText()) > diff) {
                JOptionPane.showMessageDialog(null, "Amount exceeded max limit!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            WorkRequest request = new WorkRequest();
            request.setFundType(Funds.fundsType.HealthCareFunds.getValue());
            request.setSender(account);
            enterprise.getUserAccountDirectory().getUserAccount().stream()
                    .filter(x -> x.getRole() instanceof SchoolAdminRole)
                    .forEach(x -> {
                        request.setReceiver(x);
                        request.setFundRequested(Double.parseDouble(txtAmount.getText()));
                        request.setGrantStatus("In Transit");
                        x.getWorkQueue().getWorkRequestList().add(request);
                    });
            JOptionPane.showMessageDialog(null, "Sent request to school admin!", "Sent", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox fundsCombo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtFunds;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
