/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Analytics.StateAdmin;

import Business.Network.Network;
import javax.swing.JPanel;

/**
 *
 * @author akash
 */
public class SchoolAnalyticsPage extends javax.swing.JPanel {

    /**
     * Creates new form SchoolAnalyticsPage
     */ Network network;
    JPanel userProcessContainer;
    String input;
    public SchoolAnalyticsPage( JPanel userProcessContainer,Network network,String input) {
        initComponents();
        this.network=network;
        this.userProcessContainer=userProcessContainer;
        this.input=input;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanel = new javax.swing.JPanel();
        performAnalyticsButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        performAnalyticsButton1 = new javax.swing.JButton();
        performAnalyticsButton2 = new javax.swing.JButton();
        GraphPanel = new javax.swing.JPanel();

        JPanel.setBackground(new java.awt.Color(255, 255, 255));

        performAnalyticsButton.setBackground(new java.awt.Color(255, 0, 51));
        performAnalyticsButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        performAnalyticsButton.setForeground(new java.awt.Color(255, 255, 102));
        performAnalyticsButton.setText("Fund Type");
        performAnalyticsButton.setBorder(null);
        performAnalyticsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        performAnalyticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performAnalyticsButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fund Analytics ");

        performAnalyticsButton1.setBackground(new java.awt.Color(255, 0, 51));
        performAnalyticsButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        performAnalyticsButton1.setForeground(new java.awt.Color(255, 255, 102));
        performAnalyticsButton1.setText("Funding History");
        performAnalyticsButton1.setBorder(null);
        performAnalyticsButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        performAnalyticsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performAnalyticsButton1ActionPerformed(evt);
            }
        });

        performAnalyticsButton2.setBackground(new java.awt.Color(255, 0, 51));
        performAnalyticsButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        performAnalyticsButton2.setForeground(new java.awt.Color(255, 255, 102));
        performAnalyticsButton2.setText("School Funded");
        performAnalyticsButton2.setBorder(null);
        performAnalyticsButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        performAnalyticsButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performAnalyticsButton2ActionPerformed(evt);
            }
        });

        GraphPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addComponent(performAnalyticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(performAnalyticsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(performAnalyticsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(performAnalyticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(performAnalyticsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(performAnalyticsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 123, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void performAnalyticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performAnalyticsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_performAnalyticsButtonActionPerformed

    private void performAnalyticsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performAnalyticsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_performAnalyticsButton1ActionPerformed

    private void performAnalyticsButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performAnalyticsButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_performAnalyticsButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GraphPanel;
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton performAnalyticsButton;
    private javax.swing.JButton performAnalyticsButton1;
    private javax.swing.JButton performAnalyticsButton2;
    // End of variables declaration//GEN-END:variables
}
